spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/eselpo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: XUhZtnkxB6hTsOvN5Pcblxvw2C1wBB8G
            scope: openid
            redirect-uri: http://localhost:8082/login/oauth2/code/keycloak
server:
  port: 8082
logging:
  level:
    org.springframework.security: TRACE
